FOLSPRINGB-36: Add postgres dependency to pom.xml
folio-org/folio-spring-base pull request #36
Opened 2022-01-19 00:45 UTC by librarianmage

https://issues.folio.org/projects/FOLSPRINGB/issues/FOLSPRINGB-36

## Purpose
In the base, Postgres is a dependency but it is not loaded by `pom.xml`.

2022-01-19 00:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/folio-spring-base?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/folio-spring-base?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/folio-spring-base?pullRequest=36) it.</sub>

2022-01-26 12:45 UTC, psmagin requested changes

2022-01-26 12:45 UTC, psmagin commented on pom.xml
> +      <version>${postgresql.version}</version>
```suggestion
      <scope>runtime</scope>
```
The version of postgresql should be in sync with the spring libs that working with it. So I propose to use the dependency that `spring-boot-starter-parent` provides.
Also, we can use `runtime` scope for PostgreSQL driver.

2022-01-27 20:38 UTC, librarianmage commented
Makes sense to me!

2022-01-28 12:15 UTC, psmagin approved these changes

2022-01-28 12:16 UTC, psmagin commented on pom.xml
> +    <postgresql.version>42.3.1</postgresql.version>
So this property is not needed now.

2022-02-15 22:40 UTC, librarianmage commented
Hmm, not sure why it decided that it's making all of these changes.

2022-02-15 22:45 UTC, ncovercash commented
@psmagin @dmtkachenko this should be ready for review now!

2022-02-16 09:33 UTC, psmagin commented
I suggest to merge this in master, not in release branch.

2022-02-16 16:57 UTC, ncovercash commented
@psmagin not sure how that happened, but it seems we can't change it.  Should re rebase and make a new PR?

2022-05-04 08:24 UTC, julianladisch commented
@librarianmage Thank you for your contribution! Your commits have been merged to master: #49

Therefore this pull request is no longer needed and can be closed.

2022-05-04 08:24 UTC, closed without merging