Reverting changes to provide backward compatibility, to not force tea…
folio-org/folio-spring-base pull request #67
Opened 2022-10-07 16:27 UTC by TarasSpashchenko

Reverting changes to provide backward compatibility, not to force teams to review all folio-spring-base based modules addressing this breaking change.

## Purpose
With the recent changes made with https://github.com/folio-org/folio-spring-base/pull/56, the breaking changes have been added. Because development teams do not have the extra capacity to address those changes in the scope of the Nolana release, it is necessary to provide backward compatibility to eliminate those breaking changes.

## Approach
Make two static methods within FolioExecutionScopeExecutionContextManager.java public again.

#### TODOS and Open Questions
N/A

## Learning
N/A

2022-10-07 16:29 UTC, khandramai approved these changes

2022-10-10 19:37 UTC, julianladisch requested changes
This breaking change has intentionally been introduced to force the teams to switch to the try-with-resources solution. This will result in a more secure tenant separation.

The change is trivial to implement in almost all cases, see the list at https://github.com/folio-org/folio-spring-base/pull/56#issuecomment-1167862860

There is no need to revert visibility of beginFolioExecutionContext and endFolioExecutionContext to public.

This pull request should be closed as "Won't do".

2022-10-11 09:49 UTC, TarasSpashchenko commented
Hello @julianladisch ,
It is not possible to apply all those changes to modules in the Nolana release; that is why I created this PR to provide backward compatibility.
I propose the following trade-off to solve this.
We will include this change in the Nolana release, and breaking changes will be included in the Orchid release. At the same time, could you please refresh the list of modules that uses those methods that will be removed from public access? I will create user stories for all those modules and assign them to teams to implement in the Orchid release.

2022-10-11 10:34 UTC, psmagin commented
Does it make sense to merge it into the release branch if we are going to proceed with breaking changes in the next release?

2022-10-11 11:05 UTC, TarasSpashchenko commented
@psmagin, But you need to release this library for Nolana, or not?

2022-10-11 12:38 UTC, psmagin commented
@TarasSpashchenko, it's already released: v5.0.0

2022-10-13 05:51 UTC, NikitaSedyx commented
hi @julianladisch 
any thoughts for Taras' comment? some teams can't bump up spring-base version because of this breaking change as it wasn't planned (especially when spring-base was released after deadline) and such breaking change shouldn't be introduce right before the release 1-2 weeks.

2022-10-14 20:08 UTC, merged